# This is a basic workflow to help you get started with Actions

name: UpdateMearstPortConfig

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'bin/maerskConfig.json'  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  DB-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Insert/Update DB
        working-directory: bin
        run: |
          curl -i -X POST https://procurement-core.forto.io/configs/offers-fetch/ \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{secrets.TOKEN}}" \
          -d "@maerskConfig.json"
