name: Update Mearsk Spot Port Config

on:
  push:
    paths:
      - 'bin/maerskSpotPortConfig.json'  
jobs: 
 update-collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Update sandbox collection
        if: github.ref != 'refs/heads/main'
        run: |
          curl -i -X POST https://procurement-core.forto.io/configs/offers-fetch/ \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{secrets.CLIENT_AUTHORIZATION_TOKEN_SANDBOX}}" \
          -d "@maerskSpotPortConfig.json"

      - name: Update production collection
        if: github.ref == 'refs/heads/main'
        working-directory: bin
        run: |
          curl -i -X POST https://procurement-core.forto.com/configs/offers-fetch/ \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{secrets.CLIENT_AUTHORIZATION_TOKEN_PRODUCTION}}" \
          -d "@maerskSpotPortConfig.json"
